version: '3'
name: docker_php
services:
  backend:
    container_name: docker_php_nginx_hardened
    image: mochrira/php:7.4.33-nginx-hardened
    build: 
      context: ./
      dockerfile: dockerfile
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ../examples:/var/www/html
    ports:
      - 9000:80