version: '3'
name: docker_php
services:
  backend:
    container_name: docker_php_nginx_beta
    image: mochrira/php:7.4.33-nginx
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - ../example:/var/www/html
    ports:
      - 8089:80
    environment:
      - PRODUCTION=YES
      - REINSTALL_COMPOSER=NO