FROM php:7.4.33-fpm-alpine

# installing requirements
RUN apk add --no-cache icu-dev libzip-dev libpng-dev
RUN docker-php-ext-install mysqli

# intl
RUN docker-php-ext-install intl
RUN docker-php-ext-install gd
RUN docker-php-ext-install zip

## composer
RUN php -r "copy('https://github.com/composer/getcomposer.org/raw/main/web/download/2.6.2/composer.phar', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '88c84d4a53fcf1c27d6762e1d5d6b70d57c6dc9d2e2314fd09dbf86bf61e1aef') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

## sudo, supervisor
RUN apk update
RUN apk add --no-cache nginx sudo supervisor

# Add local user
RUN addgroup -g 1000 php
RUN adduser -u 1000 -G php -D php
RUN mkdir -p /etc/sudoers.d
RUN echo "php ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/php
RUN chmod 0440 /etc/sudoers.d/php

# Configuring nginx and supervisord
RUN sed -i 's/;pidfile/pidfile/g' /etc/supervisord.conf
COPY nginx.conf /etc/nginx/http.d/default.conf
COPY supervisor.ini /etc/supervisor.d/nginx.ini

# Launch
COPY entrypoint.sh /entrypoint.sh
USER php
WORKDIR /home/php/www
ENTRYPOINT [ "/bin/sh", "/entrypoint.sh" ]