FROM php:7.4.33-fpm-alpine

# installing requirements
RUN docker-php-ext-install mysqli

# intl
RUN apk add --no-cache icu-dev
RUN docker-php-ext-install intl

## composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

## sudo, supervisor
RUN apk update
RUN apk add --no-cache nginx sudo supervisor

# Add local user
RUN addgroup -g 1000 php
RUN adduser -u 1000 -G php -D php
RUN mkdir -p /etc/sudoers.d
RUN echo "php ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/php
RUN chmod 0440 /etc/sudoers.d/php

# Configuring nginx and supervisord
RUN sed -i 's/;pidfile/pidfile/g' /etc/supervisord.conf
COPY nginx.conf /etc/nginx/http.d/default.conf
COPY supervisor.ini /etc/supervisor.d/nginx.ini

# Launch
COPY entrypoint.sh /entrypoint.sh
USER php
WORKDIR /home/php/www
ENTRYPOINT [ "/bin/sh", "/entrypoint.sh" ]