FROM php:7.4.33-fpm-alpine

# install prerequisities
RUN apk update \
    && apk add --no-cache apache2 apache2-proxy supervisor icu-dev libzip-dev libpng-dev \
    && docker-php-ext-install mysqli intl gd zip

# composer
RUN curl -fsSL 'https://github.com/composer/getcomposer.org/raw/main/web/download/2.6.2/composer.phar' -o /tmp/composer.phar \
    && echo "88c84d4a53fcf1c27d6762e1d5d6b70d57c6dc9d2e2314fd09dbf86bf61e1aef  /tmp/composer.phar" | sha256sum -c \
    && mv /tmp/composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer

# configuring snuffleupagus
RUN curl -fsSL 'https://github.com/jvoisin/snuffleupagus/archive/refs/tags/v0.9.0.zip' -o /tmp/snuffleupagus.zip \
    && echo "f7274804d2a2cf473e9b692d1f9ebf16ef39ce3d0dbd054e7423a79e3378fe3b  /tmp/snuffleupagus.zip" | sha256sum -c \
    && unzip -d /tmp /tmp/snuffleupagus.zip \
    && rm /tmp/snuffleupagus.zip \
    && docker-php-ext-configure /tmp/snuffleupagus-0.9.0/src --enable-snuffleupagus \
    && docker-php-ext-install /tmp/snuffleupagus-0.9.0/src \
    && rm -r /tmp/snuffleupagus-0.9.0 \
    && rm -r /var/cache/apk/* \
    && mkdir -p /usr/local/etc/snuffleupagus

COPY ./snuffleupagus/snuffleupagus.ini /usr/local/etc/php/conf.d/docker-php-ext-snuffleupagus.ini
COPY ./snuffleupagus/10-default.rules /usr/local/etc/snuffleupagus/10-default.rules

# configuring supervisor
RUN sed -i 's/;pidfile/pidfile/g' /etc/supervisord.conf \
    && mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini

COPY httpd.conf /etc/apache2/httpd.conf
COPY supervisor.ini /etc/supervisor.d/apache.ini

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/bin/sh", "/entrypoint.sh" ]