FROM php:7.4.33-fpm-alpine

# install prerequisities
RUN apk update \
    && apk add --no-cache apache2 apache2-proxy supervisor icu-dev libzip-dev libpng-dev \
    && docker-php-ext-install mysqli intl gd zip

# composer
RUN curl -fsSL 'https://github.com/composer/getcomposer.org/raw/main/web/download/2.6.2/composer.phar' -o /tmp/composer.phar \
    && echo "88c84d4a53fcf1c27d6762e1d5d6b70d57c6dc9d2e2314fd09dbf86bf61e1aef  /tmp/composer.phar" | sha256sum -c \
    && mv /tmp/composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer

RUN sed -i 's/;pidfile/pidfile/g' /etc/supervisord.conf \
    && sed -i 's/;user=chrism/user=root/g' /etc/supervisord.conf \
    && mv /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini

COPY httpd.conf /etc/apache2/httpd.conf
COPY supervisor.ini /etc/supervisor.d/apache.ini

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/bin/sh", "/entrypoint.sh"]